keys: w,a,s,d,shift,ctrl
name: WOT Blitz Mauschen
replays:
  end-record: None
  formating:
    filtering: true
    opencv_blur: '3'
    opencv_threshold: '120'
  resolution:
    fact: 16x9
    type: 16x9
  start-record: l
