name: "Template"      # Название игры которое будет отображаться в интерфейсе
replays:
  start-record: "l"     # Клавиша для начала записи реплея
  end-record: None      # Клавиша для окончания записи реплея (если None то таже что и для начала)