name: "Template"            # Название игры которое будет отображаться в интерфейсе
keys: w,a,s,d,shift,mouse
replays:
  start-record: "l"         # Клавиша для начала записи реплея
  end-record: None          # Клавиша для окончания записи реплея (если None то таже что и для начала)
  resolution: 
    type: custom            # Позволяет устанавливать разрешение изображение в виде пресета (16x9, 4x3, custom)
    fact: 1x1               # Фактическоре разрешение конечного изображения
  formating:
    filtering: True         # Применять ли фильтр поиска контуров
    opencv_threshold: 120   # Порог цвета для отсечения изображения
    opencv_blur: 7          # Применять ли размытие к изображению и насколько
